source 'https://rubygems.org'

gem 'jekyll', '3.3'
gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem 'jekyll-sitemap', '0.11.0'
  gem 'jekyll-seo-tag', '2.0.0'
  gem 'jekyll-feed', '0.9.2'
end